<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    public function run()
    {
        $students = [
            ['student_number' => '340527', 'name' => 'Vliet, Ruben van', 'age_group' => '<18'],
            ['student_number' => '334855', 'name' => 'Edelbroek, Danny', 'age_group' => '18-22'],
            ['student_number' => '325602', 'name' => 'Veenstra, Nicky', 'age_group' => '18-22'],
            ['student_number' => '328105', 'name' => 'Deugd, Joram de', 'age_group' => '18-22'],
            ['student_number' => '332490', 'name' => 'Badin, Prince Al', 'age_group' => '18-22'],
            ['student_number' => '338307', 'name' => 'Boers, Sylvio', 'age_group' => '18-22'],
            ['student_number' => '341524', 'name' => 'Wilde, Lucas de', 'age_group' => '<18'],
            ['student_number' => '338323', 'name' => 'Beek, Kevin van', 'age_group' => '<18'],
            ['student_number' => '342387', 'name' => 'Kemmeren, Lucas', 'age_group' => '18-22'],
            ['student_number' => '337754', 'name' => 'Baş, Mahmut', 'age_group' => '<18'],
            ['student_number' => '342350', 'name' => 'Samarasinghe, Sandil', 'age_group' => '<18'],
            ['student_number' => '338569', 'name' => 'Jong, Emile de', 'age_group' => '<18'],
            ['student_number' => '339934', 'name' => 'Haven, Lisa', 'age_group' => '<18'],
            ['student_number' => '341388', 'name' => 'Marcot, Nicoleta', 'age_group' => '18-22'],
            ['student_number' => '340453', 'name' => 'Jaber, Amr', 'age_group' => '18-22'],
            ['student_number' => '341417', 'name' => 'Hamdan, Omar', 'age_group' => '18-22'],
            ['student_number' => '342067', 'name' => 'Benchdor, Youssef', 'age_group' => '<18'],
            ['student_number' => '340225', 'name' => 'Abdalla, Abdulkadir', 'age_group' => '<18'],
            ['student_number' => '338126', 'name' => 'Houfi, Amin El', 'age_group' => '<18'],
            ['student_number' => '338127', 'name' => 'Arrasi, Achraf El', 'age_group' => '18-22'],
            ['student_number' => '341516', 'name' => 'Margai, Reda', 'age_group' => '<18'],
            ['student_number' => '342004', 'name' => 'Laassila, Yasin', 'age_group' => '<18'],
            ['student_number' => '340525', 'name' => 'Bruin, Job de', 'age_group' => '<18'],
            ['student_number' => '340528', 'name' => 'Arrindell, Nathania', 'age_group' => '<18'],
            ['student_number' => '336216', 'name' => 'Bosch, Luuk van den', 'age_group' => '18-22'],
            ['student_number' => '340310', 'name' => 'Masri, Rayan Al', 'age_group' => '<18'],
            ['student_number' => '337426', 'name' => 'Hoogland, Herman', 'age_group' => '18-22'],
            ['student_number' => '341511', 'name' => 'Geijtenbeek, Koen', 'age_group' => '18-22'],
            ['student_number' => '340524', 'name' => 'Bardai, Yassine El', 'age_group' => '<18'],
            ['student_number' => '340529', 'name' => 'Schinkel, Jim', 'age_group' => '<18'],
            ['student_number' => '342094', 'name' => 'Bel Hadi, Fahim', 'age_group' => '<18'],
            ['student_number' => '338862', 'name' => 'Shubeliev, Ivan', 'age_group' => '18-22'],
            ['student_number' => '340712', 'name' => 'Matar, Odi', 'age_group' => '23+'],
            ['student_number' => '341742', 'name' => 'Voorden, Ronan van', 'age_group' => '18-22'],
            ['student_number' => '337804', 'name' => 'Kuile, Nero ter', 'age_group' => '<18'],
            ['student_number' => '341390', 'name' => 'Balikane, Mounir', 'age_group' => '<18'],
            ['student_number' => '342355', 'name' => 'Yenice, Sümeyra', 'age_group' => '23+'],
            ['student_number' => '342357', 'name' => 'Abbas, Ahmad', 'age_group' => '18-22'],
            ['student_number' => '341657', 'name' => 'Boogaard, David van den', 'age_group' => '18-22'],
            ['student_number' => '342360', 'name' => 'Samonte, Carlo John', 'age_group' => '18-22'],
            ['student_number' => '341925', 'name' => 'Yilmaz, Gurkan', 'age_group' => '18-22'],
            ['student_number' => '335974', 'name' => 'Nieuwendijk, Thijmen', 'age_group' => '18-22'],
            ['student_number' => '339946', 'name' => 'panhuis, Sep in \'t', 'age_group' => '<18'],
            ['student_number' => '337705', 'name' => 'Kosov, Artur', 'age_group' => '18-22'],
            ['student_number' => '340306', 'name' => 'Mehrabi, Omid', 'age_group' => '18-22'],
            ['student_number' => '342504', 'name' => 'Belharch, Adam', 'age_group' => '<18'],
            ['student_number' => '340308', 'name' => 'Borgman, Wesley', 'age_group' => '<18'],
            ['student_number' => '337706', 'name' => 'Yavuz, Özer', 'age_group' => '<18'],
            ['student_number' => '337803', 'name' => 'Loul, Samir', 'age_group' => '18-22'],
            ['student_number' => '337847', 'name' => 'Vogel, Gideon', 'age_group' => '18-22'],
            ['student_number' => '338719', 'name' => 'Gadimye Zaker, Danial', 'age_group' => '18-22'],
            ['student_number' => '341391', 'name' => 'Nnodimele, Delano', 'age_group' => '18-22'],
            ['student_number' => '337805', 'name' => 'Zundert, Jamie van', 'age_group' => '18-22'],
            ['student_number' => '340458', 'name' => 'Vianen, Dylan', 'age_group' => '18-22'],
            ['student_number' => '341886', 'name' => 'Bostanci, Arda', 'age_group' => '18-22'],
            ['student_number' => '337662', 'name' => 'Khafizov, Bakka', 'age_group' => '18-22'],
            ['student_number' => '337888', 'name' => 'Almaamo, Mohammad', 'age_group' => '18-22'],
            ['student_number' => '341379', 'name' => 'Staring, Luke', 'age_group' => '18-22'],
            ['student_number' => '341512', 'name' => 'Oujamaa, Adam', 'age_group' => '18-22'],
            ['student_number' => '338255', 'name' => 'Bilt, Luuk van der', 'age_group' => '18-22'],
            ['student_number' => '342669', 'name' => 'Šabić, Eldin', 'age_group' => '18-22'],
            ['student_number' => '337934', 'name' => 'Ceulemans, Milo', 'age_group' => '18-22'],
            ['student_number' => '341381', 'name' => 'Smoorenburg, Rick', 'age_group' => '<18'],
            ['student_number' => '341124', 'name' => 'Soest, Einar van', 'age_group' => '<18'],
            ['student_number' => '338715', 'name' => 'Bayram, Batin', 'age_group' => '<18'],
            ['student_number' => '337420', 'name' => 'Spilker, Helena', 'age_group' => '18-22'],
            ['student_number' => '340452', 'name' => 'Mohammed, Mo', 'age_group' => '18-22'],
            ['student_number' => '337400', 'name' => 'Kruijf, Dylano de', 'age_group' => '18-22'],
            ['student_number' => '342349', 'name' => 'Liao, Jianyu', 'age_group' => '18-22'],
            ['student_number' => '342353', 'name' => 'Martino Molina, Hernan', 'age_group' => '18-22'],
            ['student_number' => '340611', 'name' => 'Al-Shibami, Alseddiq', 'age_group' => '18-22'],
            ['student_number' => '342539', 'name' => 'Siralkhtim, Ehab', 'age_group' => '18-22'],
            ['student_number' => '341384', 'name' => 'Krystoń, Alex', 'age_group' => '18-22'],
            ['student_number' => '341385', 'name' => 'Deijs, Mick', 'age_group' => '<18'],
            ['student_number' => '340913', 'name' => 'Siegelaer, Chavier', 'age_group' => '18-22'],
            ['student_number' => '336426', 'name' => 'Rooijen, Jasper van', 'age_group' => '18-22'],
            ['student_number' => '340408', 'name' => 'Baloche, Jahir', 'age_group' => '18-22'],
            ['student_number' => '339076', 'name' => 'Fathi, Fathi', 'age_group' => '18-22'],
            ['student_number' => '339077', 'name' => 'Donk, Simiethro', 'age_group' => '<18'],
            ['student_number' => '341521', 'name' => 'Yıldız, Mirac', 'age_group' => '<18'],
            ['student_number' => '338718', 'name' => 'Al-Barakani, Naji', 'age_group' => '18-22'],
            ['student_number' => '341509', 'name' => 'Pol, Jaya van de', 'age_group' => '<18'],
            ['student_number' => '341037', 'name' => 'Busch, Simon', 'age_group' => '18-22'],
            ['student_number' => '341042', 'name' => 'Salat, Younis', 'age_group' => '<18'],
            ['student_number' => '337598', 'name' => 'Goes, Youri', 'age_group' => '<18'],
            ['student_number' => '342358', 'name' => 'Grosu, Daniel', 'age_group' => '18-22'],
        ];

        foreach ($students as $student) {
            Student::create($student);
        }
    }
}